root = "."
tmp_dir = "/tmp/air"

[build]

  cmd = "go build -o /tmp/air/auth ./cmd/auth"
  bin = "/tmp/air/auth"

  include_dir = ["cmd", "internal"]
  include_ext = ["go"]
  exclude_dir = ["migrations", "e2e"]
  exclude_regex = ["_test\\.go"]

  delay = 300
  stop_on_error = true
  send_interrupt = true
  kill_delay = "2s"

[log]
  time = true

[misc]
  clean_on_exit = true
